name: WorldGM
main: WorldGM\WorldGM
version: 6.1
api: [1.10.0]
load: POSTWORLD
author: Exxarion
description: Set different gamemodes for certain worlds
website: http://aplus-craft.tk
commands:
 wgm:
  description: Set different gamemodes, for different worlds.
  usage: "/wgm set <gamemode> (world)\n/wgm <include/exclude> <player>\n/wgm version\n/wgm check\n/wgm gm"
  permission: worldgm.use
permissions:
 worldgm.use:
  description: "Allows users to use the plugin's features"
  default: op
