name: WorldGM
main: WorldGM\WorldGM
version: 3.0
api: [1.10.0]
load: POSTWORLD
author: Exxarion
description: Set different gamemodes for certain worlds
website: http://aplus-craft.tk
commands:
 wgm:
  description: Set different gamemodes, for different worlds.
  usage: "/wgm set <gamemode> (world)\n -OR-\n /wgm <include/exclude> <player>"
  permission: worldgm.use
permissions:
 worldgm.use:
  description: "Allows the user to set world gamemodes"
  default: op
