name: WorldGM
main: WorldGM\WorldGM
version: 3.0
api: [1.10.0]
load: POSTWORLD
author: Exxarion
description: Set different gamemodes for certain worlds
website: http://aplus-craft.tk
commands:
 wgm:
  description: Main Command.
  usage: "/wgm set <gamemode> (world)\n -OR-\n /wgm <include/exclude> <player>"
  permission: worldgm.command.wgm
permissions:
 worldgm.command.wgm:
  description: "Allows the user to set world gamemodes"
  default: op
