# __          __        _     _  _____ __  __ 
# \ \        / /       | |   | |/ ____|  \/  |
#  \ \  /\  / /__  _ __| | __| | |  __| \  / |
#   \ \/  \/ / _ \| '__| |/ _` | | |_ | |\/| |
#    \  /\  / (_) | |  | | (_| | |__| | |  | |
#     \/  \/ \___/|_|  |_|\__,_|\_____|_|  |_|
#
#
#Plugin Config file
#
excluded: [] #These are players who are not affected by World Gamemodes.
worlds: [] #Worlds that are set by the plugin will appear here.
#
