#
# __        __         _     _  ____ __  __  
# \ \      / /__  _ __| | __| |/ ___|  \/  | 
#  \ \ /\ / / _ \| '__| |/ _` | |  _| |\/| | 
#   \ V  V / (_) | |  | | (_| | |_| | |  | | 
#    \_/\_/ \___/|_|  |_|\__,_|\____|_|  |_| 
#               | |__  _   _                 
#               | '_ \| | | |                
#               | |_) | |_| |                
#  _____        |_.__/ \__, | _              
# | ____|_  ____  ____ |___/_(_) ___  _ __   
# |  _| \ \/ /\ \/ / _` | '__| |/ _ \| '_ \  
# | |___ >  <  >  < (_| | |  | | (_) | | | | 
# |_____/_/\_\/_/\_\__,_|_|  |_|\___/|_| |_| 
                                            
# WorldGM EMPTY config file
#
#
excluded: [] #These are players who are not affected by World Gamemodes.
worlds: [] #Worlds that are set by the plugin will appear here.
